# Generated by Django 2.2.10 on 2020-11-14 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_survey', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_survey', to='question.Survey')),
                ('id_user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_survey', to='question.User')),
            ],
        ),
        migrations.CreateModel(
            name='UserResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('id_answer', models.ManyToManyField(related_name='user_responses', to='question.Answer')),
                ('id_question', models.ManyToManyField(related_name='user_responses', to='question.Question')),
                ('id_user', models.ManyToManyField(related_name='user_responses', to='question.User')),
            ],
        ),
    ]
