# Generated by Django 2.2.10 on 2020-11-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20201114_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userresponses',
            name='id_answer',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_responses', to='question.Answer'),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='id_question',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_responses', to='question.Question'),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='id_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_responses', to='question.User'),
        ),
        migrations.AlterField(
            model_name='userresponses',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
